# Generated by Django 3.2.16 on 2024-01-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام اثر')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='تصویر')),
                ('des', models.TextField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
