# Generated by Django 3.2.16 on 2024-01-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jjii', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='first',
            field=models.BooleanField(blank=True, null=True, verbose_name='اولین اسلاید'),
        ),
    ]
