# Generated by Django 3.2.16 on 2024-02-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jjii', '0002_slider_first'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='نام')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع')),
                ('message', models.TextField(max_length=400, verbose_name='پیام')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=60, null=True, verbose_name='نوع محتوا')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='نام اثر')),
                ('story', models.TextField(blank=True, max_length=600, null=True, verbose_name='خلاصه داستان')),
                ('genre', models.CharField(blank=True, max_length=100, null=True, verbose_name='ژانر')),
                ('country', models.CharField(blank=True, max_length=60, null=True, verbose_name='کشور سازنده')),
                ('producer', models.CharField(blank=True, max_length=60, null=True, verbose_name='تهیه کننده')),
                ('director', models.CharField(blank=True, max_length=60, null=True, verbose_name='کارگردان')),
                ('writer', models.CharField(blank=True, max_length=60, null=True, verbose_name='نویسنده')),
                ('stars', models.TextField(blank=True, max_length=300, null=True, verbose_name='بازیگران')),
                ('language', models.TextField(blank=True, max_length=300, null=True, verbose_name='زبان')),
                ('imdblink', models.CharField(blank=True, max_length=200, null=True, verbose_name='پیوند آی ام دی بی')),
                ('imdbscore', models.CharField(blank=True, max_length=200, null=True, verbose_name='امتیاز آی ام دی بی')),
                ('host', models.TextField(blank=True, max_length=300, null=True, verbose_name='مجریان')),
                ('date', models.IntegerField(blank=True, null=True, verbose_name='سال تولید')),
                ('episode', models.IntegerField(blank=True, null=True, verbose_name='شماره اپیزود')),
                ('audience_age', models.IntegerField(blank=True, null=True, verbose_name='حد پایین سن مخاطب')),
                ('view', models.IntegerField(blank=True, default='1', null=True, verbose_name='دفعات پخش')),
                ('temp', models.IntegerField(blank=True, default='1', null=True, verbose_name='دما')),
                ('score', models.IntegerField(blank=True, default='1', null=True, verbose_name='امتیاز')),
                ('likes', models.IntegerField(blank=True, default='0', null=True, verbose_name='لایک')),
                ('dislike', models.IntegerField(blank=True, default='0', null=True, verbose_name='دیسلایک')),
                ('org', models.CharField(blank=True, max_length=80, null=True, verbose_name='شبکه یا سازمان تولید کننده')),
                ('duration', models.IntegerField(blank=True, default='0', null=True, verbose_name='مدت')),
                ('firstpage', models.BooleanField(blank=True, null=True, verbose_name='اولین اسلاید')),
                ('firstpagepriority', models.IntegerField(blank=True, default='0', null=True, verbose_name='اولویت نمایش صفحه ی اول')),
            ],
        ),
        migrations.AlterField(
            model_name='slider',
            name='des',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='توضیحات'),
        ),
    ]
