# Generated by Django 3.2.16 on 2024-02-03 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jjii', '0003_auto_20240203_0931'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Series',
            new_name='Content',
        ),
    ]
