# Generated by Django 3.2.16 on 2024-02-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jjii', '0005_content_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='فعال'),
        ),
    ]
