# Generated by Django 3.2.16 on 2024-02-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jjii', '0006_content_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='contentlink',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='پیوند محتوا'),
        ),
    ]
