# Generated by Django 3.2.16 on 2024-02-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jjii', '0007_content_contentlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='contentlink',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='پیوند محتوا بر روی سرور'),
        ),
        migrations.AlterField(
            model_name='content',
            name='firstpage',
            field=models.BooleanField(blank=True, null=True, verbose_name='اولین تصویر در اسلایدر باشد؟'),
        ),
        migrations.AlterField(
            model_name='content',
            name='firstpagepriority',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name=' اولویت نمایش صفحه ی اول در میان محتوای هم رده'),
        ),
    ]
